language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo test --verbose --workspace
  - cargo tarpaulin --ignore-tests
  - cargo clippy -- -D warnings
  - cargo fmt -- --check
  - cargo audit