[workspace]
members = [
    "api",
    "config",
    "database",
    "lib",
    "processor",
    "protobuf",
    "subscriber"
]

# TODO !!! Establish runtime/startup flow
# TODO !! Find secure ways to store keys and passwords (??)
# TODO !  Create point calculator