version: '2.1'

services:
  archer-processor:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: archer-processor
    container_name: archer-processor
    volumes:
      - '.:/archer'
    command: cargo run

  archer-rest-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: archer-rest-api
    container_name: archer-rest-api
    volumes:
      - .:/archer
    ports:
      - '8000:8000'
    command: cargo run

  archer-subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    image: archer-subscriber
    container_name: archer-subscriber
    volumes:
      - '.:/archer'
    depends_on:
      - postgres
    command: cargo run

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator:1.2
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawset proposal create -k /root/.sawtooth/keys/my_key.priv \
            sawtooth.consensus.algorithm.name=Devmode \
            sawtooth.consensus.algorithm.version=0.1 \
            -o config.batch
          sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050
      "

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.2
    expose:
      - 5050
    ports:
      - '5050:5050'
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust --connect tcp://validator:5050

  postgres:
    image: postgres:alpine
    container_name: archer-postgres
    restart: always
    environment:
      POSTGRES_USER: acharette
      POSTGRES_PASSWORD: c3ntr4lc0mm4nd1!
      POSTGRES_DB: archer_test
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: archer-adminer
    restart: always
    ports:
      - '8080:8080'