[package]
name = "archer-protobuf"
version = "0.1.0"
authors = ["Alexander Charette <acharette.wake@gmail.com>"]
edition = "2018"

[build-dependencies]
protobuf-codegen-pure = "2.18.0"

[dependencies]
archer = { path = "../lib" }
protobuf = "2.18.0"