[package]
name = "archer-config"
version = "0.1.0"
authors = ["Alexander Charette <acharette.wake@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.10.1"

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

